yatube/about/urls.py
from django.urls import path

from about import views
from about.apps import AboutConfig

app_name = AboutConfig.name

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.contrib.auth import views
from django.urls import path

from users.views import SignUp

app_name = 'users'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='signup'),
    path(
        'logout/',
        views.LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout',
    ),
    path(
        'login/',
        views.LoginView.as_view(template_name='users/login.html'),
        name='login',
    ),
    path(
        'password_reset_form/',
        views.PasswordResetView.as_view(
            template_name='users/password_reset_form.html',
        ),
        name='password_reset_form',
    ),
    path(
        'password_change_form/',
        views.PasswordChangeView.as_view(
            template_name='users/password_change_form.html',
        ),
        name='password_change_form',
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from about.apps import AboutConfig
from posts.apps import PostsConfig
from users.apps import UsersConfig

urlpatterns = [
    path('', include('posts.urls', namespace=PostsConfig.name)),
    path('about/', include('about.urls', namespace=AboutConfig.name)),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace=UsersConfig.name)),
    path('auth/', include('django.contrib.auth.urls')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied_view'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>
    © {{ year }} Copyright <span style="color:red">Ya</span>tube
  </p>
</footer>

yatube/templates/includes/header.html
<header>
  {% load static %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}"
             width="30"
             height="30"
             class="d-inline-block align-top"
             alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.view_name  == 'about:author' %} active {% endif %}"
             href="{% url 'about:author' %}">
            Об авторе
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.resolver_match.view_name  == 'about:tech' %} active {% endif %}"
             href="{% url 'about:tech' %}">
            Технологии
          </a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.view_name  == 'posts:post_create' %} active {% endif %}"
               href="{% url 'posts:post_create' %}">
              Новая запись
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.view_name  == 'users:password_change_form' %} active {% endif %}"
               href="{% url 'users:password_change_form' %}">
              Изменить пароль
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li>Пользователь: {{ user.username }}</li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.view_name  == 'users:login' %} active {% endif %}"
               href="{% url 'users:login' %}">
              Войти
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.view_name  == 'users:signup' %} active {% endif %}"
               href="{% url 'users:signup' %}">
              Регистрация
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
</header>

yatube/templates/includes/post_cart.html
<article>
  <ul>
    <li>Автор: {{ post.author.get_full_name }}</li>
    <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
  </ul>
  <p>{{ post.text }}</p>
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
</article>